import { Component, EventEmitter, OnInit, Output } from '@angular/core';

@Component({
	selector: 'app-icon-picker',
	templateUrl: './icon-picker.component.html',
	styleUrls: ['./icon-picker.component.scss'],
})
export class IconPickerComponent implements OnInit {
	items = [

		{ Name: 'address-book', Tags: 'address,book' },
		{ Name: 'address-card', Tags: 'address,card' },
		{ Name: 'city', Tags: 'city' },
		{ Name: 'clipboard-list', Tags: 'clipboard,list' },
		{ Name: 'contract', Tags: 'contract' },
		{ Name: 'industry', Tags: 'industry' },

		{ Name: 'inventory', Tags: 'inventory,wms,warehouse' },
		{ Name: 'landmark', Tags: 'landmark,store' },
		{ Name: 'money-check', Tags: 'money,check,card' },
		{ Name: 'moto', Tags: 'moto' },
		{ Name: 'pallet', Tags: 'pallet' },
		{ Name: 'shipping-fast', Tags: 'shipping,van,truck' },
		{ Name: 'signature', Tags: 'signature' },
		{ Name: 'sitemap', Tags: 'sitemap' },
		{ Name: 'truck-outline', Tags: 'truck,van' },
		{ Name: 'truck', Tags: 'truck,van' },
		{ Name: 'user-tie', Tags: 'user,tie' },
		{ Name: 'warehouse', Tags: 'warehouse,inventory,wms' },

		{ Name: 'accessibility', Tags: 'accessibility' },
		{ Name: 'add', Tags: 'add,circle,include,invite,plus' },
		{ Name: 'add-circle', Tags: 'add,circle,include,invite,plus' },
		{ Name: 'airplane', Tags: 'airplane,plane' },
		{ Name: 'alarm', Tags: 'alarm,clock,time' },
		{ Name: 'albums', Tags: 'albums,boxes,slides,square' },
		{ Name: 'alert', Tags: '!,alert,attention,exclamation,notice,warning' },
		{
			Name: 'alert-circle',
			Tags: '!,alert,attention,circle,exclamation,notice,warning',
		},
		{ Name: 'american-football', Tags: 'american,football' },
		{ Name: 'analytics', Tags: 'analytics,data,metrics,track' },
		{
			Name: 'aperture',
			Tags: 'aperture,dark,images,levels,light,settings',
		},
		{ Name: 'apps', Tags: 'applications,apps' },
		{ Name: 'archive', Tags: 'archive,email' },
		{ Name: 'arrow-back', Tags: 'arrow,back,chevron,left,navigation' },
		{
			Name: 'arrow-back-circle',
			Tags: 'arrow,back,chevron,circle,left,navigation',
		},
		{ Name: 'arrow-down', Tags: 'arrow,chevron,down' },
		{ Name: 'arrow-down-circle', Tags: 'arrow,chevron,circle,down' },
		{
			Name: 'arrow-forward',
			Tags: 'arrow,chevron,forward,navigation,right',
		},
		{
			Name: 'arrow-forward-circle',
			Tags: 'arrow,chevron,circle,forward,navigation,right',
		},
		{ Name: 'arrow-redo', Tags: 'arrow,redo' },
		{ Name: 'arrow-redo-circle', Tags: 'arrow,circle,redo' },
		{ Name: 'arrow-undo', Tags: 'arrow,undo' },
		{ Name: 'arrow-undo-circle', Tags: 'arrow,circle,undo' },
		{ Name: 'arrow-up', Tags: 'arrow,chevron,up' },
		{ Name: 'arrow-up-circle', Tags: 'arrow,chevron,circle,up' },
		{ Name: 'at', Tags: '@,at' },
		{ Name: 'at-circle', Tags: '@,at,circle' },
		{ Name: 'attach', Tags: 'attach' },
		{ Name: 'backspace', Tags: 'backspace' },
		{ Name: 'bag', Tags: 'bag' },
		{ Name: 'bag-add', Tags: 'add,bag' },
		{ Name: 'bag-check', Tags: 'bag,check' },
		{ Name: 'bag-handle', Tags: 'bag,handle' },
		{ Name: 'bag-remove', Tags: 'bag,remove' },
		{ Name: 'balloon', Tags: 'balloon' },
		{ Name: 'ban', Tags: 'ban' },
		{ Name: 'bandage', Tags: 'bandage' },
		{ Name: 'barbell', Tags: 'barbell,exercise,lifting,weight' },
		{ Name: 'barcode', Tags: 'barcode,camera,reader' },
		{ Name: 'bar-chart', Tags: 'bar,chart' },
		{ Name: 'baseball', Tags: 'baseball' },
		{ Name: 'basket', Tags: 'basket' },
		{ Name: 'basketball', Tags: 'basketball' },
		{ Name: 'battery-charging', Tags: 'battery,charging' },
		{ Name: 'battery-dead', Tags: 'battery,dead' },
		{ Name: 'battery-full', Tags: 'battery,full' },
		{ Name: 'battery-half', Tags: 'battery,half' },
		{ Name: 'beaker', Tags: 'beaker,flask,mixture,potion' },
		{ Name: 'bed', Tags: 'bed,hotel,sleep' },
		{ Name: 'beer', Tags: 'beer,drink,eat,food' },
		{ Name: 'bicycle', Tags: 'bicycle,bike,exercise' },
		{ Name: 'bluetooth', Tags: 'bluetooth,cloud,connection' },
		{ Name: 'boat', Tags: 'boat' },
		{ Name: 'body', Tags: 'body' },
		{ Name: 'bonfire', Tags: 'bonfire,heat,hot' },
		{ Name: 'book', Tags: 'book,read' },
		{ Name: 'bookmark', Tags: 'bookmark,favorite,save,tag' },
		{ Name: 'bookmarks', Tags: 'bookmarks,favorite' },
		{ Name: 'bowling-ball', Tags: 'ball,bowling' },
		{ Name: 'briefcase', Tags: 'briefcase,folder,organize' },
		{ Name: 'browsers', Tags: 'browsers,square' },
		{ Name: 'brush', Tags: 'brush' },
		{ Name: 'bug', Tags: 'bug,develop,error,hacker,program' },
		{ Name: 'build', Tags: 'build' },
		{ Name: 'bulb', Tags: 'bulb' },
		{ Name: 'bus', Tags: 'bus' },
		{ Name: 'business', Tags: 'business' },
		{ Name: 'cafe', Tags: 'cafe,coffee,cup' },
		{ Name: 'calculator', Tags: 'arithmetic,calculator,math' },
		{ Name: 'calendar', Tags: 'calendar,date,month,week' },
		{ Name: 'calendar-clear', Tags: 'calendar,clear' },
		{ Name: 'calendar-number', Tags: 'calendar,number' },
		{ Name: 'call', Tags: 'call,telephone' },
		{ Name: 'camera', Tags: 'camera,image,photo' },
		{ Name: 'camera-reverse', Tags: 'camera,reverse' },
		{ Name: 'car', Tags: 'car' },
		{
			Name: 'card',
			Tags: '$,card,cash,credit,debit,dollars,money,price,shopping',
		},
		{ Name: 'caret-back', Tags: 'arrow,back,caret' },
		{ Name: 'caret-back-circle', Tags: 'arrow,back,caret,circle' },
		{ Name: 'caret-down', Tags: 'arrow,caret,down' },
		{ Name: 'caret-down-circle', Tags: 'arrow,caret,circle,down' },
		{ Name: 'caret-forward', Tags: 'arrow,caret,forward,right' },
		{
			Name: 'caret-forward-circle',
			Tags: 'arrow,caret,circle,forward,right',
		},
		{ Name: 'caret-up', Tags: 'arrow,caret,up' },
		{ Name: 'caret-up-circle', Tags: 'arrow,caret,circle,up' },
		{ Name: 'car-sport', Tags: 'car,sport' },
		{ Name: 'cart', Tags: 'cart' },
		{
			Name: 'cash',
			Tags: '$,cash,credit,debit,dollars,money,price,shopping',
		},
		{ Name: 'cellular', Tags: 'cellular' },
		{ Name: 'clipboard', Tags: 'clipboard,copy,paste,write' },
		{ Name: 'close', Tags: 'circle,close,delete,remove' },
		{ Name: 'close-circle', Tags: 'circle,close,delete,remove' },
		{ Name: 'cloud', Tags: 'circle,cloud,storage,weather,whether' },
		{ Name: 'cloud-circle', Tags: 'circle,cloud,storage,weather,whether' },
		{ Name: 'cloud-done', Tags: 'cloud,done' },
		{ Name: 'cloud-download', Tags: 'cloud,download,storage' },
		{ Name: 'cloud-offline', Tags: 'cloud,offline' },
		{ Name: 'cloud-upload', Tags: 'cloud,storage,upload' },
		{ Name: 'cloudy', Tags: 'cloudy,overcast,weather,whether' },
		{ Name: 'cloudy-night', Tags: 'cloudy,night,overcast,weather,whether' },
		{ Name: 'code', Tags: 'code,develop,hacker,program' },
		{ Name: 'code-download', Tags: 'code,develop,download,hacker,program' },
		{ Name: 'code-slash', Tags: 'code,slash' },
		{ Name: 'code-working', Tags: 'code,develop,hacker,program,working' },
		{ Name: 'cog', Tags: 'cog,gear,options,settings' },
		{ Name: 'color-fill', Tags: 'color,fill' },
		{ Name: 'color-filter', Tags: 'color,filter' },
		{ Name: 'color-palette', Tags: 'color,palette' },
		{ Name: 'color-wand', Tags: 'color,wand' },
		{ Name: 'compass', Tags: 'compass,directions,location,navigation' },
		{ Name: 'construct', Tags: 'construct' },
		{ Name: 'contract', Tags: 'contract' },
		{
			Name: 'contrast',
			Tags: 'contrast,dark,images,levels,light,settings',
		},
		{ Name: 'copy', Tags: 'copy,duplicate,paper' },
		{ Name: 'create', Tags: 'create,edit' },
		{ Name: 'crop', Tags: 'crop' },
		{ Name: 'cube', Tags: 'box,container,cube,square' },
		{ Name: 'cut', Tags: 'cut' },
		{ Name: 'chatbox', Tags: 'chatbox' },
		{ Name: 'chatbox-ellipses', Tags: 'chatbox,ellipses' },
		{ Name: 'chatbubble', Tags: 'chatbubble' },
		{ Name: 'chatbubble-ellipses', Tags: 'chatbubble,ellipses' },
		{ Name: 'chatbubbles', Tags: 'chatbubbles,talk' },
		{ Name: 'checkbox', Tags: 'checkbox' },
		{ Name: 'checkmark', Tags: 'checkmark,circle' },
		{ Name: 'checkmark-circle', Tags: 'checkmark,circle' },
		{ Name: 'checkmark-done', Tags: 'checkmark,done' },
		{ Name: 'checkmark-done-circle', Tags: 'checkmark,circle,done' },
		{ Name: 'chevron-back', Tags: 'arrow,back,chevron,left' },
		{ Name: 'chevron-back-circle', Tags: 'arrow,back,chevron,circle,left' },
		{ Name: 'chevron-collapse', Tags: 'chevron,collapse' },
		{ Name: 'chevron-down', Tags: 'arrow,chevron,down' },
		{ Name: 'chevron-down-circle', Tags: 'arrow,chevron,circle,down' },
		{ Name: 'chevron-expand', Tags: 'chevron,expand' },
		{ Name: 'chevron-forward', Tags: 'arrow,chevron,forward,right' },
		{
			Name: 'chevron-forward-circle',
			Tags: 'arrow,chevron,circle,forward,right',
		},
		{ Name: 'chevron-up', Tags: 'arrow,chevron,up' },
		{ Name: 'chevron-up-circle', Tags: 'arrow,chevron,circle,up' },
		{ Name: 'desktop', Tags: 'desktop' },
		{ Name: 'diamond', Tags: 'diamond' },
		{ Name: 'dice', Tags: 'dice' },
		{ Name: 'disc', Tags: 'cd,disc,vinyl' },
		{ Name: 'document', Tags: 'document,file,paper' },
		{ Name: 'document-attach', Tags: 'attach,document' },
		{ Name: 'document-lock', Tags: 'document,lock' },
		{ Name: 'documents', Tags: 'documents' },
		{ Name: 'document-text', Tags: 'document,text' },
		{ Name: 'download', Tags: 'download,export' },
		{ Name: 'duplicate', Tags: 'duplicate' },
		{ Name: 'ear', Tags: 'ear' },
		{ Name: 'earth', Tags: 'earth,globe' },
		{ Name: 'easel', Tags: 'easel' },
		{ Name: 'egg', Tags: 'baby,bird,birth,egg,twitter' },
		{ Name: 'ellipse', Tags: 'circle,ellipse' },
		{ Name: 'ellipsis-horizontal', Tags: 'ellipsis,horizontal' },
		{
			Name: 'ellipsis-horizontal-circle',
			Tags: 'circle,ellipsis,horizontal',
		},
		{ Name: 'ellipsis-vertical', Tags: 'ellipsis,vertical' },
		{ Name: 'ellipsis-vertical-circle', Tags: 'circle,ellipsis,vertical' },
		{ Name: 'enter', Tags: 'enter' },
		{ Name: 'exit', Tags: 'exit' },
		{ Name: 'expand', Tags: 'expand,resize' },
		{ Name: 'extension-puzzle', Tags: 'extension,puzzle' },
		{ Name: 'eye', Tags: 'exposed,eye,look,see,view' },
		{ Name: 'eyedrop', Tags: 'eyedrop' },
		{ Name: 'eye-off', Tags: 'eye,off' },
		{ Name: 'fast-food', Tags: 'fast,food' },
		{ Name: 'female', Tags: 'dudette,female,girl,lady,woman' },
		{ Name: 'file-tray', Tags: 'file,tray' },
		{ Name: 'file-tray-full', Tags: 'file,full,tray' },
		{ Name: 'file-tray-stacked', Tags: 'file,stacked,tray' },
		{ Name: 'film', Tags: 'film' },
		{ Name: 'filter', Tags: 'filter' },
		{ Name: 'filter-circle', Tags: 'circle,filter' },
		{ Name: 'finger-print', Tags: 'finger,print' },
		{ Name: 'fish', Tags: 'fish' },
		{ Name: 'fitness', Tags: 'fitness' },
		{ Name: 'flag', Tags: 'favorite,flag,marker' },
		{ Name: 'flame', Tags: 'fire,flame,heat,hot' },
		{ Name: 'flash', Tags: 'flash,lightning,weather,whether' },
		{ Name: 'flashlight', Tags: 'flashlight' },
		{ Name: 'flash-off', Tags: 'flash,off' },
		{ Name: 'flask', Tags: 'bubbles,flask,mixture,potion' },
		{ Name: 'flower', Tags: 'flower' },
		{ Name: 'folder', Tags: 'file,folder' },
		{ Name: 'folder-open', Tags: 'folder,open' },
		{ Name: 'football', Tags: 'football,soccer' },
		{ Name: 'footsteps', Tags: 'footsteps' },
		{ Name: 'funnel', Tags: 'funnel,sort' },
		{ Name: 'game-controller', Tags: 'controller,game' },
		{ Name: 'glasses', Tags: 'glasses,look,reading,see,steve' },
		{ Name: 'globe', Tags: 'globe,internet,world' },
		{ Name: 'golf', Tags: 'golf' },
		{ Name: 'grid', Tags: 'grid,menu' },
		{ Name: 'gift', Tags: 'gift' },
		{ Name: 'git-branch', Tags: 'branch,git' },
		{ Name: 'git-commit', Tags: 'commit,git' },
		{ Name: 'git-compare', Tags: 'compare,git' },
		{ Name: 'git-merge', Tags: 'git,merge' },
		{ Name: 'git-network', Tags: 'git,network' },
		{ Name: 'git-pull-request', Tags: 'git,pull,request' },
		{ Name: 'hammer', Tags: 'hammer,options,settings,tools' },
		{ Name: 'hand-left', Tags: 'hand,left' },
		{ Name: 'hand-right', Tags: 'hand,right' },
		{ Name: 'happy', Tags: 'fun,good,happy,like,smile,yes' },
		{ Name: 'hardware-chip', Tags: 'chip,hardware' },
		{ Name: 'headset', Tags: 'headset' },
		{ Name: 'heart', Tags: 'heart,love' },
		{ Name: 'heart-circle', Tags: 'circle,heart,love' },
		{ Name: 'heart-dislike', Tags: 'dislike,heart,love' },
		{ Name: 'heart-dislike-circle', Tags: 'circle,dislike,heart,love' },
		{ Name: 'heart-half', Tags: 'half,heart,love' },
		{ Name: 'help', Tags: '?,circle,help,information,question' },
		{ Name: 'help-buoy', Tags: '?,buoy,help,question' },
		{ Name: 'help-circle', Tags: '?,circle,help,information,question' },
		{ Name: 'home', Tags: 'home,house' },
		{ Name: 'hourglass', Tags: 'hourglass,time' },
		{ Name: 'ice-cream', Tags: 'cream,ice' },
		{ Name: 'id-card', Tags: 'card,id' },
		{ Name: 'image', Tags: 'camera,image,photo' },
		{ Name: 'images', Tags: 'images,photo' },
		{ Name: 'infinite', Tags: 'forever,infinite,loop' },
		{ Name: 'information', Tags: 'circle,help,information,knowledge' },
		{
			Name: 'information-circle',
			Tags: 'circle,help,information,knowledge',
		},
		{ Name: 'invert-mode', Tags: 'invert,mode' },
		{ Name: 'journal', Tags: 'journal' },
		{ Name: 'key', Tags: 'access,key' },
		{ Name: 'keypad', Tags: 'keypad,type' },
		{ Name: 'language', Tags: 'language' },
		{ Name: 'laptop', Tags: 'apple,laptop,macbook,osx' },
		{ Name: 'layers', Tags: 'layers' },
		{ Name: 'leaf', Tags: 'green,leaf,nature,plant,recycle' },
		{ Name: 'library', Tags: 'library' },
		{ Name: 'link', Tags: 'anchor,attach,chain,href,link' },
		{ Name: 'list', Tags: 'list' },
		{ Name: 'list-circle', Tags: 'circle,list' },
		{ Name: 'locate', Tags: 'gps,locate,maps,navigate' },
		{ Name: 'location', Tags: 'location' },
		{ Name: 'lock-closed', Tags: 'closed,lock' },
		{ Name: 'lock-open', Tags: 'lock,open' },
		{ Name: 'log-in', Tags: 'login,signin' },
		{ Name: 'logo-alipay', Tags: 'alipay,logo' },
		{ Name: 'logo-amazon', Tags: 'amazon,logo' },
		{ Name: 'logo-amplify', Tags: 'amplify,logo' },
		{ Name: 'logo-android', Tags: 'android,logo' },
		{ Name: 'logo-angular', Tags: 'angular,logo' },
		{ Name: 'logo-apple', Tags: 'apple,logo' },
		{ Name: 'logo-apple-appstore', Tags: 'apple,appstore,logo' },
		{ Name: 'logo-apple-ar', Tags: 'apple,ar,logo' },
		{ Name: 'logo-behance', Tags: 'behance,logo' },
		{ Name: 'logo-bitbucket', Tags: 'bitbucket,logo' },
		{ Name: 'logo-bitcoin', Tags: 'bitcoin,logo' },
		{ Name: 'logo-buffer', Tags: 'buffer,logo' },
		{ Name: 'logo-capacitor', Tags: 'capacitor,logo' },
		{ Name: 'logo-closed-captioning', Tags: 'captioning,closed,logo' },
		{ Name: 'logo-codepen', Tags: 'codepen,logo' },
		{ Name: 'logo-css3', Tags: 'css3,logo' },
		{ Name: 'logo-chrome', Tags: 'chrome,logo' },
		{ Name: 'logo-designernews', Tags: 'designernews,logo' },
		{ Name: 'logo-deviantart', Tags: 'deviantart,logo' },
		{ Name: 'logo-discord', Tags: 'discord,logo' },
		{ Name: 'logo-docker', Tags: 'docker,logo' },
		{ Name: 'logo-dribbble', Tags: 'dribbble,logo' },
		{ Name: 'logo-dropbox', Tags: 'dropbox,logo' },
		{ Name: 'logo-edge', Tags: 'edge,logo' },
		{ Name: 'logo-electron', Tags: 'electron,logo' },
		{ Name: 'logo-euro', Tags: 'euro,logo' },
		{ Name: 'logo-facebook', Tags: 'facebook,logo' },
		{ Name: 'logo-figma', Tags: 'figma,logo' },
		{ Name: 'logo-firebase', Tags: 'firebase,logo' },
		{ Name: 'logo-firefox', Tags: 'firefox,logo' },
		{ Name: 'logo-flickr', Tags: 'flickr,logo' },
		{ Name: 'logo-foursquare', Tags: 'foursquare,logo' },
		{ Name: 'logo-google', Tags: 'google,logo' },
		{ Name: 'logo-google-playstore', Tags: 'google,logo,playstore' },
		{ Name: 'logo-gitlab', Tags: 'gitlab,logo' },
		{ Name: 'logo-github', Tags: 'github,logo' },
		{ Name: 'logo-hackernews', Tags: 'hackernews,logo' },
		{ Name: 'logo-html5', Tags: 'html5,logo' },
		{ Name: 'logo-instagram', Tags: 'instagram,logo' },
		{ Name: 'logo-ionic', Tags: 'ionic,logo' },
		{ Name: 'logo-ionitron', Tags: 'ionitron,logo' },
		{ Name: 'logo-javascript', Tags: 'javascript,logo' },
		{ Name: 'logo-laravel', Tags: 'laravel,logo' },
		{ Name: 'logo-linkedin', Tags: 'linkedin,logo' },
		{ Name: 'logo-markdown', Tags: 'logo,markdown' },
		{ Name: 'logo-mastodon', Tags: 'logo,mastodon' },
		{ Name: 'logo-medium', Tags: 'logo,medium' },
		{ Name: 'logo-microsoft', Tags: 'logo,microsoft' },
		{ Name: 'logo-nodejs', Tags: 'logo,nodejs' },
		{ Name: 'logo-no-smoking', Tags: 'logo,no,smoking' },
		{ Name: 'logo-npm', Tags: 'logo,npm' },
		{ Name: 'logo-octocat', Tags: 'logo,octocat' },
		{ Name: 'logo-paypal', Tags: 'logo,paypal' },
		{ Name: 'logo-pinterest', Tags: 'logo,pinterest' },
		{ Name: 'logo-playstation', Tags: 'logo,playstation' },
		{ Name: 'logo-pwa', Tags: 'logo,pwa' },
		{ Name: 'logo-python', Tags: 'logo,python' },
		{ Name: 'logo-react', Tags: 'logo,react' },
		{ Name: 'logo-reddit', Tags: 'logo,reddit' },
		{ Name: 'logo-rss', Tags: 'logo,rss' },
		{ Name: 'logo-sass', Tags: 'logo,sass' },
		{ Name: 'logo-skype', Tags: 'logo,skype' },
		{ Name: 'logo-slack', Tags: 'logo,slack' },
		{ Name: 'logo-snapchat', Tags: 'logo,snapchat' },
		{ Name: 'logo-soundcloud', Tags: 'logo,soundcloud' },
		{ Name: 'logo-stackoverflow', Tags: 'logo,stackoverflow' },
		{ Name: 'logo-steam', Tags: 'logo,steam' },
		{ Name: 'logo-stencil', Tags: 'logo,stencil' },
		{ Name: 'logo-tableau', Tags: 'logo,tableau' },
		{ Name: 'logo-tiktok', Tags: 'logo,tiktok' },
		{ Name: 'logo-tumblr', Tags: 'logo,tumblr' },
		{ Name: 'logo-tux', Tags: 'logo,tux' },
		{ Name: 'logo-twitch', Tags: 'logo,twitch' },
		{ Name: 'logo-twitter', Tags: 'logo,twitter' },
		{ Name: 'logo-usd', Tags: 'logo,usd' },
		{ Name: 'log-out', Tags: 'logout,signout' },
		{ Name: 'logo-venmo', Tags: 'logo,venmo' },
		{ Name: 'logo-vercel', Tags: 'logo,vercel' },
		{ Name: 'logo-vimeo', Tags: 'logo,vimeo' },
		{ Name: 'logo-vk', Tags: 'logo,vk' },
		{ Name: 'logo-vue', Tags: 'logo,vue' },
		{ Name: 'logo-web-component', Tags: 'component,logo,web' },
		{ Name: 'logo-wechat', Tags: 'logo,wechat' },
		{ Name: 'logo-whatsapp', Tags: 'logo,whatsapp' },
		{ Name: 'logo-windows', Tags: 'logo,windows' },
		{ Name: 'logo-wordpress', Tags: 'logo,wordpress' },
		{ Name: 'logo-xbox', Tags: 'logo,xbox' },
		{ Name: 'logo-xing', Tags: 'logo,xing' },
		{ Name: 'logo-yahoo', Tags: 'logo,yahoo' },
		{ Name: 'logo-yen', Tags: 'logo,yen' },
		{ Name: 'logo-youtube', Tags: 'logo,youtube' },
		{ Name: 'magnet', Tags: 'attraction,magnet,sticky' },
		{ Name: 'mail', Tags: 'email,mail' },
		{ Name: 'mail-open', Tags: 'mail,open' },
		{ Name: 'mail-unread', Tags: 'mail,unread' },
		{ Name: 'male', Tags: 'boy,dude,guy,male' },
		{ Name: 'male-female', Tags: 'female,male' },
		{ Name: 'man', Tags: 'boy,dude,guy,male,man' },
		{ Name: 'map', Tags: 'gps,map,navigation,pin' },
		{ Name: 'medal', Tags: 'medal' },
		{ Name: 'medical', Tags: 'medical' },
		{ Name: 'medkit', Tags: 'case,disease,firstaid,health,medkit,sick' },
		{ Name: 'megaphone', Tags: 'megaphone' },
		{ Name: 'menu', Tags: 'menu' },
		{ Name: 'mic', Tags: 'mic,noise,sound,speaker,talk' },
		{ Name: 'mic-circle', Tags: 'circle,mic,noise,sound,speaker,talk' },
		{ Name: 'mic-off', Tags: 'mic,noise,off,sound,speaker,talk' },
		{
			Name: 'mic-off-circle',
			Tags: 'circle,mic,noise,off,sound,speaker,talk',
		},
		{ Name: 'moon', Tags: 'dark,moon,night,sky' },
		{ Name: 'move', Tags: 'move' },
		{
			Name: 'musical-note',
			Tags: 'listening,musical,noise,note,play,sound',
		},
		{
			Name: 'musical-notes',
			Tags: 'listening,musical,noise,notes,play,sound',
		},
		{ Name: 'navigate', Tags: 'gps,location,map,navigate,pin' },
		{
			Name: 'navigate-circle',
			Tags: 'circle,gps,location,map,navigate,pin',
		},
		{ Name: 'newspaper', Tags: 'newspaper' },
		{ Name: 'notifications', Tags: 'notifications' },
		{ Name: 'notifications-circle', Tags: 'circle,notifications' },
		{ Name: 'notifications-off', Tags: 'notifications,off' },
		{ Name: 'notifications-off-circle', Tags: 'circle,notifications,off' },
		{ Name: 'nuclear', Tags: 'danger,hazard,nuclear,warning' },
		{ Name: 'nutrition', Tags: 'nutrition' },
		{ Name: 'open', Tags: 'open,external,anchor,link' },
		{ Name: 'options', Tags: 'options' },
		{ Name: 'paper-plane', Tags: 'paper,plane' },
		{ Name: 'partly-sunny', Tags: 'partly,sunny' },
		{ Name: 'pause', Tags: 'break,freeze,hold,music,pause' },
		{ Name: 'pause-circle', Tags: 'break,circle,freeze,hold,music,pause' },
		{ Name: 'paw', Tags: 'paw' },
		{ Name: 'pencil', Tags: 'pencil' },
		{ Name: 'people', Tags: 'head,human,people,person,stalker,users' },
		{
			Name: 'people-circle',
			Tags: 'circle,head,human,people,person,stalker,users',
		},
		{ Name: 'person', Tags: 'head,human,person,staff,users' },
		{
			Name: 'person-add',
			Tags: 'add,head,human,member,new,person,staff,users',
		},
		{ Name: 'person-circle', Tags: 'circle,head,human,person,staff,users' },
		{ Name: 'person-remove', Tags: 'person,remove' },
		{ Name: 'pie-chart', Tags: 'chart,pie' },
		{ Name: 'pin', Tags: 'gps,location,navigation,pin' },
		{ Name: 'pint', Tags: 'pint' },
		{ Name: 'pizza', Tags: 'drink,eat,food,pizza' },
		{ Name: 'planet', Tags: 'globe,home,nature,planet,space,world' },
		{ Name: 'play', Tags: 'arrow,music,play,right,watch' },
		{ Name: 'play-back', Tags: 'back,left,play' },
		{ Name: 'play-back-circle', Tags: 'back,circle,left,play' },
		{ Name: 'play-circle', Tags: 'arrow,circle,music,play,right,watch' },
		{ Name: 'play-forward', Tags: 'forward,play,right' },
		{ Name: 'play-forward-circle', Tags: 'circle,forward,play,right' },
		{ Name: 'play-skip-back', Tags: 'back,left,play,skip' },
		{ Name: 'play-skip-back-circle', Tags: 'back,circle,left,play,skip' },
		{ Name: 'play-skip-forward', Tags: 'forward,play,skip' },
		{
			Name: 'play-skip-forward-circle',
			Tags: 'circle,forward,play,right,skip',
		},
		{ Name: 'podium', Tags: 'award,compete,competition,lose,podium,win' },
		{ Name: 'power', Tags: 'off,on,power' },
		{ Name: 'pricetag', Tags: '$,commerce,items,money,pricetag,shopping' },
		{
			Name: 'pricetags',
			Tags: '$,commerce,items,money,pricetags,shopping',
		},
		{ Name: 'print', Tags: 'fax,print' },
		{ Name: 'prism', Tags: 'prism' },
		{ Name: 'pulse', Tags: 'hot,live,pulse,rate' },
		{ Name: 'push', Tags: 'push' },
		{ Name: 'phone-landscape', Tags: 'landscape,phone' },
		{ Name: 'phone-portrait', Tags: 'phone,portrait' },
		{ Name: 'qr-code', Tags: 'code,qr' },
		{ Name: 'radio', Tags: 'music,radio' },
		{ Name: 'radio-button-off', Tags: 'button,off,radio' },
		{ Name: 'radio-button-on', Tags: 'button,on,radio' },
		{ Name: 'rainy', Tags: 'cloud,rainy,water,weather,whether' },
		{ Name: 'reader', Tags: 'reader' },
		{ Name: 'receipt', Tags: 'receipt' },
		{ Name: 'recording', Tags: 'film,recording,tape,voicemail' },
		{ Name: 'refresh', Tags: 'circle,refresh,reload,renew,reset' },
		{ Name: 'refresh-circle', Tags: 'circle,refresh,reload,renew,reset' },
		{ Name: 'reload', Tags: 'reload' },
		{ Name: 'reload-circle', Tags: 'circle,reload' },
		{ Name: 'remove', Tags: 'circle,minus,remove,subtract' },
		{ Name: 'remove-circle', Tags: 'circle,minus,remove,subtract' },
		{ Name: 'reorder-four', Tags: 'four,reorder' },
		{ Name: 'reorder-two', Tags: 'reorder,two' },
		{ Name: 'reorder-three', Tags: 'reorder,three' },
		{ Name: 'repeat', Tags: 'repeat' },
		{ Name: 'resize', Tags: 'resize' },
		{ Name: 'restaurant', Tags: 'eat,restaurant' },
		{ Name: 'return-down-back', Tags: 'back,down,left,return' },
		{ Name: 'return-down-forward', Tags: 'down,forward,return,right' },
		{ Name: 'return-up-back', Tags: 'back,left,return,up' },
		{ Name: 'return-up-forward', Tags: 'forward,return,right,up' },
		{ Name: 'ribbon', Tags: 'ribbon' },
		{ Name: 'rocket', Tags: 'rocket' },
		{ Name: 'rose', Tags: 'flower,rose' },
		{ Name: 'sad', Tags: 'bad,cry,no,sad' },
		{ Name: 'save', Tags: 'save' },
		{ Name: 'scale', Tags: 'scale' },
		{ Name: 'scan', Tags: 'scan' },
		{ Name: 'scan-circle', Tags: 'circle,scan' },
		{ Name: 'school', Tags: 'school' },
		{ Name: 'search', Tags: 'glass,magnifying,search' },
		{ Name: 'search-circle', Tags: 'circle,glass,magnifying,search' },
		{ Name: 'send', Tags: 'email,paper,send' },
		{ Name: 'server', Tags: 'server' },
		{ Name: 'settings', Tags: 'options,settings' },
		{ Name: 'shapes', Tags: 'shapes' },
		{ Name: 'share', Tags: 'share' },
		{ Name: 'share-social', Tags: 'share,social' },
		{ Name: 'shield', Tags: 'shield' },
		{ Name: 'shield-checkmark', Tags: 'checkmark,shield' },
		{ Name: 'shield-half', Tags: 'half,shield' },
		{ Name: 'shirt', Tags: 'shirt' },
		{ Name: 'shuffle', Tags: 'random,shuffle' },
		{ Name: 'skull', Tags: 'skull' },
		{ Name: 'snow', Tags: 'cold,snow' },
		{ Name: 'sparkles', Tags: 'sparkles' },
		{ Name: 'speedometer', Tags: 'drive,level,speed,speedometer' },
		{ Name: 'square', Tags: 'square' },
		{ Name: 'star', Tags: 'favorite,star' },
		{ Name: 'star-half', Tags: 'favorite,half,rate,star' },
		{ Name: 'stats-chart', Tags: 'chart,stats' },
		{ Name: 'stop', Tags: 'stop' },
		{ Name: 'stop-circle', Tags: 'circle,stop' },
		{ Name: 'stopwatch', Tags: 'stopwatch,time' },
		{ Name: 'storefront', Tags: 'storefront' },
		{ Name: 'subway', Tags: 'subway' },
		{ Name: 'sunny', Tags: 'light,sky,sunny,weather,whether' },
		{ Name: 'swap-horizontal', Tags: 'horizontal,swap' },
		{ Name: 'swap-vertical', Tags: 'swap,vertical' },
		{ Name: 'sync', Tags: 'sync' },
		{ Name: 'sync-circle', Tags: 'circle,sync' },
		{ Name: 'tablet-landscape', Tags: 'landscape,tablet' },
		{ Name: 'tablet-portrait', Tags: 'portrait,tablet' },
		{ Name: 'telescope', Tags: 'telescope' },
		{ Name: 'tennisball', Tags: 'tennisball' },
		{ Name: 'terminal', Tags: 'terminal' },
		{ Name: 'text', Tags: 'text' },
		{ Name: 'ticket', Tags: 'ticket' },
		{ Name: 'time', Tags: 'clock,hour,minute,second,time,watch' },
		{ Name: 'timer', Tags: 'clock,timer' },
		{ Name: 'today', Tags: 'today' },
		{ Name: 'toggle', Tags: 'switch,toggle' },
		{ Name: 'tv', Tags: 'television,tv' },
		{
			Name: 'thermometer',
			Tags: 'cold,heat,hot,mercury,temperature,thermometer',
		},
		{ Name: 'thumbs-down', Tags: 'down,thumbs' },
		{ Name: 'thumbs-up', Tags: 'thumbs,up' },
		{
			Name: 'thunderstorm',
			Tags: 'cloudy,lightning,overcast,rain,sky,storm,thunderstorm,weather,whether',
		},
		{ Name: 'trail-sign', Tags: 'sign,trail' },
		{ Name: 'train', Tags: 'train' },
		{ Name: 'transgender', Tags: 'transgender' },
		{ Name: 'trash', Tags: 'close,delete,remove,trash' },
		{ Name: 'trash-bin', Tags: 'bin,trash' },
		{ Name: 'trending-down', Tags: 'down,trending' },
		{ Name: 'trending-up', Tags: 'trending,up' },
		{ Name: 'triangle', Tags: 'triangle' },
		{ Name: 'trophy', Tags: 'award,compete,competition,lose,trophy,win' },
		{ Name: 'umbrella', Tags: 'dry,rain,shelter,umbrella,wet' },
		{ Name: 'unlink', Tags: 'unlink' },
		{ Name: 'videocam', Tags: 'camera,film,movie,videocam' },
		{ Name: 'videocam-off', Tags: 'off,videocam' },
		{ Name: 'volume-high', Tags: 'high,volume' },
		{ Name: 'volume-low', Tags: 'low,volume' },
		{ Name: 'volume-medium', Tags: 'medium,volume' },
		{ Name: 'volume-mute', Tags: 'mute,sound,volume' },
		{ Name: 'volume-off', Tags: 'off,volume' },
		{ Name: 'walk', Tags: 'walk' },
		{ Name: 'wallet', Tags: 'cash,money,wallet' },
		{ Name: 'warning', Tags: 'warning' },
		{ Name: 'watch', Tags: 'watch' },
		{ Name: 'water', Tags: 'water' },
		{ Name: 'wifi', Tags: 'bars,connection,internet,wifi' },
		{ Name: 'wine', Tags: 'glass,wine' },
		{ Name: 'woman', Tags: 'dudette,female,girl,lady,woman' },
	];
	@Output() selected = new EventEmitter();
	keyword = '';
	constructor() {}

	ngOnInit() {}
	onSelected(event) {
		this.selected.emit(event);
	}
}
